# Generated by Django 4.2.2 on 2023-06-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_remove_student_user_remove_teacher_user"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classattend",
            name="student_id",
            field=models.ForeignKey(on_delete=models.Model, to="user.user"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
