# Generated by Django 4.2.2 on 2023-06-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_client_name'),
        ('course', '0002_alter_classattend_student_id_alter_course_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default='2023-06-26'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classattend',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
        migrations.AddField(
            model_name='course',
            name='division_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='course.division'),
            preserve_default=False,
        ),
    ]
