# Generated by Django 4.2.2 on 2023-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_division_course_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='division_name',
            new_name='division_id',
        ),
    ]
