# Generated by Django 4.2.2 on 2023-06-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_division_id_course_division_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.CharField(max_length=20),
        ),
    ]
