# Generated by Django 4.2.2 on 2023-06-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_student_birth_date_alter_student_gender_and_more'),
        ('course', '0006_delete_division_alter_course_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='division_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.division'),
        ),
    ]
