# Generated by Django 4.2.2 on 2023-06-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_teacher_id_course_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='minute',
            new_name='hours',
        ),
    ]
