# Generated by Django 4.2.2 on 2023-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_minute_course_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattend',
            name='submit_survey',
            field=models.BooleanField(default=False),
        ),
    ]
