# Generated by Django 4.2.2 on 2023-06-28 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_classattend_submit_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
