# Generated by Django 4.2.2 on 2023-06-28 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_classattend_attend_state_alter_classattend_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattend',
            name='end_at',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
