# Generated by Django 4.2.2 on 2023-07-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_classattend_end_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classattend',
            name='submit_survey',
        ),
    ]
