# Generated by Django 4.2.2 on 2023-07-03 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_remove_classattend_submit_survey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classattend",
            name="start_at",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
