# Generated by Django 4.2.2 on 2023-06-28 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_minute_course_hours'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSurveyReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply1', models.CharField(max_length=300)),
                ('reply2', models.CharField(max_length=300)),
                ('reply3', models.CharField(max_length=300)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
