# Generated by Django 4.2.2 on 2023-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_fixedsurveyreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question_num',
        ),
        migrations.RemoveField(
            model_name='surveyreply',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='surveyreply',
            name='reply_num',
        ),
        migrations.AddField(
            model_name='survey',
            name='question1',
            field=models.CharField(default='없음', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question2',
            field=models.CharField(default='없음', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question3',
            field=models.CharField(default='없음', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply1',
            field=models.TextField(default='없음'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply2',
            field=models.TextField(default='없음'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply3',
            field=models.TextField(default='없음'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FixedSurveyReply',
        ),
    ]
