# Generated by Django 4.2.2 on 2023-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_survey_question_remove_survey_question_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyreply',
            name='reply2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyreply',
            name='reply3',
            field=models.TextField(blank=True),
        ),
    ]
