# Generated by Django 4.2.2 on 2023-06-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_classattend_submit_survey'),
        ('survey', '0004_alter_survey_question2_alter_survey_question3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
