# Generated by Django 4.2.2 on 2023-07-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_student_birth_date_alter_student_gender_and_more'),
        ('survey', '0005_alter_survey_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyreply',
            name='student_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='submit_survey',
            field=models.BooleanField(default=False),
        ),
    ]
