# Generated by Django 4.2.2 on 2023-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveyreply_student_id_surveyreply_submit_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
