# Generated by Django 4.2.2 on 2023-10-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_question10_survey_question4_survey_question5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question13',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question14',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='question15',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyreply',
            name='reply15',
            field=models.TextField(blank=True),
        ),
    ]
