# Generated by Django 4.2.2 on 2023-06-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_classattend_student_id_alter_course_teacher_id"),
        ("user", "0002_user_remove_student_user_remove_teacher_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(name="Student",),
        migrations.DeleteModel(name="Teacher",),
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
