# Generated by Django 4.2.2 on 2023-06-27 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자'), ('O', '기타')], max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='qr_code',
            field=models.ImageField(upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.division'),
        ),
    ]
