# Generated by Django 4.2.2 on 2023-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_student_birth_date_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_course_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
