# Generated by Django 4.2.2 on 2023-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_student_current_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_course_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
