# Generated by Django 4.2.2 on 2023-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_student_current_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_course_name',
            field=models.CharField(default='수강중인 강의 없음', max_length=20, null=True),
        ),
    ]
