# Generated by Django 4.2.2 on 2023-09-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_student_current_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.division'),
        ),
    ]
